name: Build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  push:
    branches:
    - master
    - main
    - dev
    - preview
    - v*
  paths:
  - "src/**"
  - ".github/workflows/**"

#env:
#  NugetApiKey: ${{secrets.NUGETAPIKEY}}
#  TwitterConsumerKey: ${{secrets.TWITTER_CONSUMER_KEY}}
# TwitterConsumerSecret: ${{secrets.TWITTER_CONSUMER_SECRET}}
#  TwitterAccessToken: ${{secrets.TWITTER_ACCESS_TOKEN}}
#  TwitterAccessTokenSecret: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
#  DiscordToken: ${{secrets.DISCORD_TOKEN}}
#  DiscordGuildId: '679761126598115336'
#  DiscordChannelId: '803717285986566174'
#  MastodonClientId: ${{secrets.MASTODON_CLIENT_ID}}
#  MastodonClientSecret: ${{secrets.MASTODON_CLIENT_SECRET}}
#  MastodonInstance: 'dotnet.social'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          fetch-depth: 0

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '8.0.x'

    - uses: AdoptOpenJDK/install-jdk@v1
      with:
        version: '13'
        architecture: x64

    - name: Add .NET Workloads
      run: dotnet workload install maui

    - name: Build
      run: dotnet build Build.slnf /restore -m -property:Configuration=Release -property:PublicRelease=true

    - name: Post NuGet Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nuget-artifacts
        path: '**/*.nupkg'

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nugets
        path: ${{ github.workspace }}/artifacts
        retention-days: 5

    - name: Publish NuGets
      if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGETAPIKEY }} --skip-duplicate

    - name: Install NerdBank.GitVersioning CLI
      if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v') }}
      run: dotnet tool install -g nbgv

    - name: Get Nuget Version from Nerdbank
      run: nbgv get-version

    #https://shinylib.net/release-notes/mobile/
    #this.GitVersioningGetVersion().NuGetPackageVersion - Nerdbank versioning in cake
    - name: Announce to Mastodon
      if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v') }}
      uses: cbrgm/mastodon-github-action@v2
      with:
        access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} # access token
        url: ${{ secrets.MASTODON_URL }}
        message: "Hello from GitHub Actions!"

    - name: 'Announce to X/Twitter'
      uses: ethomson/send-tweet-action@v1
      with:
        status: "Hi, this is a test!"
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}